### ISSUE TITLE
Interesting failure - I think PID-related but not sure

### ISSUE THREAD

**Issue by OConnorStP** [MacMiniVault/Mac-Scripts#18]
Hi all,

I started getting the dreaded PID failures on an install that I did yesterday.  So I decided to clear out the old stuff and rerun the script.  Here's the result.  I'll really stomp on it this time and see if I can get a clean install, but thought you might be interested in this failure-mode.  Here's the terminal session:

server:mysql admin$ bash <(curl -Ls http://git.io/eUx7rg)
Downloading MySQL Installers ... may take a few moments
######################################################################## 100.0%
...
...
Installing MySQL, administrator password required ...
Password:
installer: Package name is MySQL 5.6.22-community
installer: choices changes file '/Users/admin/Downloads/MySQL-install.plist' applied
installer: Upgrading at base path /
installer: The upgrade was successful.
...
...
DO YOU WANT TO LOAD MySQL ON BOOT? [Y/n]Y
/Library/LaunchDaemons/com.mysql.server.plist: Operation already in progress
mkdir: /var/mysql: File exists
ln: /var/mysql/mysql.sock: File exists
/usr/local/mysql/support-files/mysql.server: line 362: pidof: command not found
/dev/fd/63: line 146: SORRY, MySQL IS NOT RUNNING ... THERE MUST BE A PROBLEM: command not found

[so at this point I decided to give it a kick, just for fun -- and mysql starts and stops OK -- I think I'll clear all the cruft out, RESTART, and then rerun the script]

server:mysql admin$ sudo /usr/local/mysql/support-files/mysql.server start
Password:
Starting MySQL
.. SUCCESS! 
server:mysql admin$ sudo /usr/local/mysql/support-files/mysql.server stop
Shutting down MySQL
.. SUCCESS!

**Comment by jonschwenn** [comment]
It's extremely difficult to remove all aspects of MySQL.  MySQL does not have an uninstaller and we will not attempt to create one.  Based on your output, the installer from MySQL sees the old version and your sock file and start up plist fail because they were already present.  It all crumbles around that point.  MySQL may be running at this point, but the startup scripts, control panel, and some aspects of it may not be functional.

If there are any previous versions of MySQL - or this OS started as 10.6 Server or earlier where MySQL was pre-installed - then the install can not be guaranteed to go smoothly.  The only way we can guarantee it is with a fresh OS install.

**Comment by jonschwenn** [comment]
It's extremely difficult to remove all aspects of MySQL.  MySQL does not have an uninstaller and we will not attempt to create one.  Based on your output, the installer from MySQL sees the old version and your sock file and start up plist fail because they were already present.  It all crumbles around that point.  MySQL may be running at this point, but the startup scripts, control panel, and some aspects of it may not be functional.

If there are any previous versions of MySQL - or this OS started as 10.6 Server or earlier where MySQL was pre-installed - then the install can not be guaranteed to go smoothly.  The only way we can guarantee it is with a fresh OS install.

**Comment by OConnorStP** [comment]
Ah!  Very helpful hints there with references to the sock file and the LaunchDaemon.  I've added those to my punchlist of stuff to remove.  I'll give that a go and see how it works.  Thanks,  FYI, here's the list as it stands so far:

move the old databases from /usr/local/mysql to someplace else

rename the old base mysql directory 

move MySQL.Com out of /Library/StartupItems

move MY* out of /Library/PreferencePanes
move MY* out of Admin's /Library/PreferencePanes

edit /etc/hostconfig and remove the line MYSQLCOM=-YES-

remove the alias for mysql in /usr/local/

remove receipts for mysql in /Library/Receipts/
remove receipts for mysql in /private/var/db/receipts/

remove the MYSQL_PASSWORD item from the desktop if it's there (left over from previous runs of the script)

remove references to var/mysql/mysql.sock and etc/mysql.sock

remove mysql-related plists from /Library/LaunchDaemons/
