### ISSUE TITLE
ElCapitan Issue

### ISSUE THREAD

**Issue by vdhub** [MacMiniVault/Mac-Scripts#29]
Hello, 

I installed the last git script for mysql on el capitan and it seems that it works until the pc restarts , once restarted i can connect locally but i cannot connect from the network to the server anymore. 

So , 

I run the script, i add the users, i add the host, the database and so on, i connect to the database, all ok. Once i restart the pc where the server resides local works ok, remote no more. 

Any idea ? 

Just as an update, if i go in the System Preferences on the MySQL panel it states that it is Running, while if it go on the command line and i run ./mysql.server status i get " ERROR! MySQL is not running"

So i guess the panel and the script are running 2 different states or something wrong here .

**Comment by vdhub** [comment]
It seems that the latest installed version it uses 3307 instead of 3306 , if i use the new port it works ok.

**Comment by ajleach** [comment]
Hello vdhub,

Thank you for the report - until OS X 10.11 has been released and we've worked out any bugs, we have temporarily removed the ability to install the script on 10.11.

**Comment by vdhub** [comment]
Thanks for your update, please update the link for the new SequelPro update if possible, they fixed a lot of issues and it is more stable now. 

Thanks again .

**Comment by nrollr** [comment]
Agree with vdhub, script should pack Sequel Pro [Release 1.1](http://www.sequelpro.com/release-notes) instead of Release 1.0.2

**mmvmysql.sh** - [line 128](https://github.com/MacMiniVault/Mac-Scripts/blob/master/mmvMySQL/mmvmysql.sh#L128), the new download path should be: https://github.com/sequelpro/sequelpro/releases/download/release-1.1/sequel-pro-1.1.dmg

thnx
